# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 680df407e7f188d0908e0974fbde18f9252b6c477456b33411cc88d4743330e0e36e02a492708f22b3bb4dc3616d2af136c5762bfb49424cfee7b2db8a7b7857

test:
  secret_key_base: 55b0fba2cb01462e9aa4700da4235134fd9d745eb232042155d257c03a1c4265ae7051e85271ef5bd8729defcda50d495ac43edb9fd1d13de370d369d1283dba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
